INSERT INTO store(logradouro, nome, telefone, endereco, horarios, ftp_url)
VALUES
('Shopping Cidade Jardim', 'Lupo', '(0xx) xxxx-xxxx', 'Av. Magalhaes de Castro, 12000 - Cidade Jardim, Sao Paulo', '10h as 22h', 'rappi.lupo_cj'),
-- ('Shopping Cidade Jardim', 'Lupo', '(0xx) xxxx-xxxx', 'Av. Magalhaes de Castro, 12000 - Cidade Jardim, Sao Paulo', '10h as 22h', 'rappi.lupo_cj'),
('Rua Augusta', 'Corello', '(0xx) xxxx-xxxx', 'R. Augusta, 2466 - Cerqueira César, São Paulo - SP', '9h as 20h', 'rappi.corello_augusta'),
('Rua Oscar Freire', 'Corello', '(0xx) xxxx-xxxx', 'Rua Oscar Freire, 935 - Jardim Paulista, Sao Paulo - SP', '10h as 20h', 'rappi.corello_oscarfreire');


INSERT INTO corello(id_store, codigo_barra, descricao_cor_produto, tamanho, grade, produto, estoque, reserva, estoque_final, codigo_tab_preco, preco1, tipo_produto, descricao_produto, descricao_produto_nf, grupo_produto, subgrupo_produto, linha, marca, unidade, peso, referencia_fabricante, fabricante, estilista, sexo_tipo, ultima_saida, ultima_entrada, filial, cor_produto, colecao, origem, material, data_cadastramento, descricao_produto_completa, corredor_template, sub_corredor_template, nome_do_produto_template, descricao_do_produto_template, preco_do_produto_template, filled_template)
VALUES
(4, '0994807802202838','COURO ATANADO BRIC','1','38','9948078022','1','0','1','01','249.90','CALCADO','SANDALIA MINIMAL PLAIN','CALCADOS CORELLO CORDELLO','CALCADO','SANDALIA','CORDELLO','CORELLO','PAR','0.460','9948078','ZENGLEIN E CIA LTDA','','None','2019-05-03 12:22:14.670000','2019-04-11 00:00:00','18 - OSCAR FREIRE','028','OI2019','0','None','2019-03-15 00:00:00','SANDALIA MINIMAL PLAIN COURO ATANADO BRIC 38','Calcado','Sandalia','Sandalia Feminina Minimal Plain - Couro Atanado Bric 33','Sandalia Feminina Minimal Plain. A sandalia Minimal Plain e confeccionada em couro, com tiras largas, fecho no calcanhar e salto bloco estilo flare, oferecendo charme, conforto e seguranca para o calcado. E perfeita para looks casuais urbanos compondo com saias e vestidos. Curiosidades Corello. O salto bloco, conhecido tambem como Block Heels, foi o queridinho das mulheres na decada de 70 e se tornou uma forte tendencia retro. O salto bloco, alem de super charmoso e confortavel, por ser mais largo e “quadradao”, oferece uma maior estabilidade ao caminhar, tornando-se aliado de quem tem uma rotina mais corrida','249.90', true),
(4, '0994807802202139','COURO ATANADO PRETO','1','39','9948078022','1','0','1','01','249.90','CALCADO','SANDALIA MINIMAL PLAIN','CALCADOS CORELLO CORDELLO','CALCADO','SANDALIA','CORDELLO','CORELLO','PAR','0.460','9948078','ZENGLEIN E CIA LTDA','','None','2019-04-27 00:00:00','2019-04-20 00:00:00','18 - OSCAR FREIRE','021','OI2019','0','None','2019-03-15 00:00:00','SANDALIA MINIMAL PLAIN COURO ATANADO PRETO 39','Calcado','Sandalia','Sandalia Feminina Minimal Plain - Couro Atanado Preto 33','Sandalia Feminina Minimal Plain. A sandalia Minimal Plain e confeccionada em couro, com tiras largas, fecho no calcanhar e salto bloco estilo flare, oferecendo charme, conforto e seguranca para o calcado. E perfeita para looks casuais urbanos compondo com saias e vestidos. Curiosidades Corello. O salto bloco, conhecido tambem como Block Heels, foi o queridinho das mulheres na decada de 70 e se tornou uma forte tendencia retro. O salto bloco, alem de super charmoso e confortavel, por ser mais largo e “quadradao”, oferece uma maior estabilidade ao caminhar, tornando-se aliado de quem tem uma rotina mais corrida','249.90', true),
(4, '0994807802202134','COURO ATANADO PRETO','1','34','9948078022','1','0','1','01','249.90','CALCADO','SANDALIA MINIMAL PLAIN','CALCADOS CORELLO CORDELLO','CALCADO','SANDALIA','CORDELLO','CORELLO','PAR','0.460','9948078','ZENGLEIN E CIA LTDA','','None','2019-04-27 00:00:00','2019-04-20 00:00:00','18 - OSCAR FREIRE','021','OI2019','0','None','2019-03-15 00:00:00','SANDALIA MINIMAL PLAIN COURO ATANADO PRETO 34','Calcado','Sandalia','Sandalia Feminina Minimal Plain - Couro Atanado Preto 33','Sandalia Feminina Minimal Plain. A sandalia Minimal Plain e confeccionada em couro, com tiras largas, fecho no calcanhar e salto bloco estilo flare, oferecendo charme, conforto e seguranca para o calcado. E perfeita para looks casuais urbanos compondo com saias e vestidos. Curiosidades Corello. O salto bloco, conhecido tambem como Block Heels, foi o queridinho das mulheres na decada de 70 e se tornou uma forte tendencia retro. O salto bloco, alem de super charmoso e confortavel, por ser mais largo e “quadradao”, oferece uma maior estabilidade ao caminhar, tornando-se aliado de quem tem uma rotina mais corrida','249.90', true),
(4, '0994807802202135','COURO ATANADO PRETO','1','35','9948078022','2','0','2','01','249.90','CALCADO','SANDALIA MINIMAL PLAIN','CALCADOS CORELLO CORDELLO','CALCADO','SANDALIA','CORDELLO','CORELLO','PAR','0.460','9948078','ZENGLEIN E CIA LTDA','','None','2019-04-27 00:00:00','2019-04-20 00:00:00','18 - OSCAR FREIRE','021','OI2019','0','None','2019-03-15 00:00:00','SANDALIA MINIMAL PLAIN COURO ATANADO PRETO 35','Calcado','Sandalia','Sandalia Feminina Minimal Plain - Couro Atanado Preto 33','Sandalia Feminina Minimal Plain. A sandalia Minimal Plain e confeccionada em couro, com tiras largas, fecho no calcanhar e salto bloco estilo flare, oferecendo charme, conforto e seguranca para o calcado. E perfeita para looks casuais urbanos compondo com saias e vestidos. Curiosidades Corello. O salto bloco, conhecido tambem como Block Heels, foi o queridinho das mulheres na decada de 70 e se tornou uma forte tendencia retro. O salto bloco, alem de super charmoso e confortavel, por ser mais largo e “quadradao”, oferece uma maior estabilidade ao caminhar, tornando-se aliado de quem tem uma rotina mais corrida','249.90', true);